import React, { useEffect, useMemo, useState } from 'react';
import {
  BrainCircuit,
  Search,
  AlertTriangle,
  CheckCircle2
} from 'lucide-react';
import { useTheme } from '../context/ThemeContext';

export const ExplainableAiPage = ({
  users = [],
  events = [],
  incidents = [],
  onSelectUser
}) => {
  const { isDark } = useTheme();
  const [searchQuery, setSearchQuery] = useState('');
  const [xaiReasons, setXaiReasons] = useState([]);
  const [prediction, setPrediction] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const latestMLData = useMemo(() => {
    const mlEvents = events
      .filter(
        event =>
          Array.isArray(event.xaiReasons) &&
          event.xaiReasons.length > 0
      )
      .sort(
        (a, b) =>
          new Date(b.timestamp || 0) -
          new Date(a.timestamp || 0)
      );

    return mlEvents[0] || null;
  }, [events]);

  useEffect(() => {
    if (latestMLData?.xaiReasons) {
      setXaiReasons(latestMLData.xaiReasons);
      setPrediction({
        riskScore: latestMLData.riskScore,
        threatProbability:
          latestMLData.mlThreatProbability ||
          latestMLData.mlAnomalyScore,
        contextualRiskScore:
          latestMLData.contextualRiskScore,
        trustScore: latestMLData.trustScore,
        policyAction: latestMLData.policyAction,
        policyReason: latestMLData.policyReason
      });
    }
  }, [latestMLData]);

  const filteredReasons = useMemo(() => {
    const query = searchQuery.trim().toLowerCase();

    if (!query) {
      return xaiReasons;
    }

    return xaiReasons.filter(reason => {
      const feature = String(
        reason.feature || ''
      ).toLowerCase();

      const value = String(
        reason.value ?? ''
      ).toLowerCase();

      const impact = String(
        reason.impact || ''
      ).toLowerCase();

      const shapValue = String(
        reason.shap_value ?? ''
      ).toLowerCase();

      return (
        feature.includes(query) ||
        value.includes(query) ||
        impact.includes(query) ||
        shapValue.includes(query)
      );
    });
  }, [xaiReasons, searchQuery]);

  const formatFeatureName = feature => {
    if (!feature) {
      return 'Unknown Feature';
    }

    return String(feature)
      .replace(/_/g, ' ')
      .replace(/\b\w/g, char =>
        char.toUpperCase()
      );
  };

  const formatValue = value => {
    if (value === null || value === undefined) {
      return 'N/A';
    }

    if (typeof value === 'number') {
      return Number.isInteger(value)
        ? value.toString()
        : value.toFixed(4);
    }

    return String(value);
  };

  const formatShapValue = value => {
    const numericValue = Number(value);

    if (!Number.isFinite(numericValue)) {
      return 'N/A';
    }

    return `${numericValue >= 0 ? '+' : ''}${numericValue.toFixed(4)}`;
  };

  const isIncreasingThreat = reason => {
    return reason?.impact === 'increases threat';
  };

  const hasMLData = xaiReasons.length > 0;

  return (
    <div className="space-y-10">
      <div
        className={`p-8 sm:p-10 border border-[#D4AF37]/25 relative transition-colors ${
          isDark ? 'bg-black' : 'bg-white'
        }`}
      >
        <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-6 relative z-10">
          <div>
            <div className="flex items-center gap-3 mb-3">
              <span className="text-[10px] font-mono tracking-[0.25em] uppercase text-[#D4AF37] border border-[#D4AF37]/40 px-2.5 py-0.5">
                EXPLAINABLE AI (XAI)
              </span>

              <span className="text-[11px] font-mono text-gray-500">
                SHAP / TREE ATTRIBUTION ENGINE
              </span>
            </div>

            <h1 className="font-serif-display text-3xl sm:text-4xl lg:text-5xl font-light tracking-tight">
              Why was this activity considered risky?
            </h1>

            <p className="text-xs text-gray-400 max-w-2xl mt-3 font-sans leading-relaxed">
              Risk predictions are explained using the feature contributions generated by the machine learning model.
            </p>
          </div>

          <div className="text-right font-mono text-xs">
            <span className="text-gray-500">
              EVALUATED FACTORS:{' '}
            </span>

            <span className="text-[#D4AF37] font-bold">
              {xaiReasons.length}
            </span>
          </div>
        </div>
      </div>

      {prediction && (
        <div
          className={`p-6 border border-[#D4AF37]/20 ${
            isDark ? 'bg-[#0A0C10]' : 'bg-white'
          }`}
        >
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            <div>
              <span className="text-[10px] font-mono uppercase tracking-[0.2em] text-gray-500">
                RISK SCORE
              </span>

              <p className="text-2xl font-mono text-[#D4AF37] mt-1">
                {Number.isFinite(
                  Number(prediction.riskScore)
                )
                  ? Number(prediction.riskScore).toFixed(2)
                  : 'N/A'}
              </p>
            </div>

            <div>
              <span className="text-[10px] font-mono uppercase tracking-[0.2em] text-gray-500">
                THREAT PROBABILITY
              </span>

              <p className="text-2xl font-mono text-[#D4AF37] mt-1">
                {Number.isFinite(
                  Number(
                    prediction.threatProbability
                  )
                )
                  ? (
                      Number(
                        prediction.threatProbability
                      ) * 100
                    ).toFixed(2) + '%'
                  : 'N/A'}
              </p>
            </div>

            <div>
              <span className="text-[10px] font-mono uppercase tracking-[0.2em] text-gray-500">
                TRUST SCORE
              </span>

              <p className="text-2xl font-mono text-[#D4AF37] mt-1">
                {Number.isFinite(
                  Number(prediction.trustScore)
                )
                  ? Number(
                      prediction.trustScore
                    ).toFixed(2)
                  : 'N/A'}
              </p>
            </div>

            <div>
              <span className="text-[10px] font-mono uppercase tracking-[0.2em] text-gray-500">
                POLICY ACTION
              </span>

              <p className="text-sm font-mono text-[#D4AF37] mt-2 uppercase">
                {prediction.policyAction || 'N/A'}
              </p>
            </div>
          </div>
        </div>
      )}

      <div
        className={`p-4 border border-[#D4AF37]/20 flex flex-col sm:flex-row gap-4 items-center justify-between ${
          isDark ? 'bg-[#0A0C10]' : 'bg-white'
        }`}
      >
        <div className="relative w-full sm:w-80">
          <input
            type="text"
            value={searchQuery}
            onChange={e =>
              setSearchQuery(e.target.value)
            }
            placeholder="Search ML features..."
            className={`w-full border text-xs pl-9 pr-3 py-2 outline-none font-mono transition-all ${
              isDark
                ? 'bg-black border-[#D4AF37]/30 text-white focus:border-[#D4AF37]'
                : 'bg-[#F9F9F7] border-gray-300 text-black focus:border-[#D4AF37]'
            }`}
          />

          <Search className="w-3.5 h-3.5 text-[#D4AF37] absolute left-3 top-1/2 -translate-y-1/2" />
        </div>

        <div className="text-[10px] font-mono text-gray-500">
          {filteredReasons.length} MODEL CONTRIBUTION
          {filteredReasons.length === 1 ? '' : 'S'}
        </div>
      </div>

      {!hasMLData && (
        <div
          className={`p-10 border border-[#D4AF37]/20 text-center ${
            isDark ? 'bg-black' : 'bg-white'
          }`}
        >
          <BrainCircuit className="w-10 h-10 text-[#D4AF37] mx-auto mb-4" />

          <h3 className="font-serif-display text-2xl font-light">
            No XAI data available
          </h3>

          <p className="text-xs text-gray-500 mt-2 font-mono">
            SHAP explanations will appear here when the ML
            service generates prediction data.
          </p>
        </div>
      )}

      {hasMLData && filteredReasons.length === 0 && (
        <div
          className={`p-10 border border-[#D4AF37]/20 text-center ${
            isDark ? 'bg-black' : 'bg-white'
          }`}
        >
          <Search className="w-8 h-8 text-[#D4AF37] mx-auto mb-4" />

          <h3 className="font-serif-display text-2xl font-light">
            No matching ML factors
          </h3>

          <p className="text-xs text-gray-500 mt-2 font-mono">
            Try another feature or value.
          </p>
        </div>
      )}

      <div className="space-y-6">
        {filteredReasons.map((reason, index) => {
          const increasesThreat =
            isIncreasingThreat(reason);

          return (
            <div
              key={`${reason.feature}-${index}`}
              className={`p-6 sm:p-8 border transition-all duration-200 ${
                isDark ? 'bg-black' : 'bg-white'
              } ${
                increasesThreat
                  ? 'border-red-500/40 hover:border-red-500'
                  : 'border-[#D4AF37]/25 hover:border-[#D4AF37]'
              }`}
            >
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-4 border-b border-[#D4AF37]/15">
                <div className="flex items-center gap-3">
                  <span className="w-6 h-6 border border-[#D4AF37]/50 flex items-center justify-center font-mono text-[11px] text-[#D4AF37]">
                    {String(index + 1).padStart(2, '0')}
                  </span>

                  <div>
                    <h3 className="font-serif-display text-2xl font-light tracking-tight">
                      {formatFeatureName(
                        reason.feature
                      )}
                    </h3>

                    <span className="text-[10px] font-mono text-gray-500">
                      FEATURE: {reason.feature || 'N/A'}
                    </span>
                  </div>
                </div>

                <div className="flex items-center gap-3">
                  <span
                    className={`text-xs font-mono font-semibold ${
                      increasesThreat
                        ? 'text-red-400'
                        : 'text-[#D4AF37]'
                    }`}
                  >
                    SHAP {formatShapValue(
                      reason.shap_value
                    )}
                  </span>

                  <span
                    className={`text-[10px] font-mono px-2 py-0.5 border uppercase font-bold ${
                      increasesThreat
                        ? 'border-red-500 text-red-400 bg-red-500/10'
                        : 'border-gray-500 text-gray-400'
                    }`}
                  >
                    {reason.impact || 'N/A'}
                  </span>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-6">
                <div className="space-y-1.5">
                  <span className="text-[10px] font-mono uppercase tracking-[0.2em] text-[#D4AF37] block">
                    MODEL FEATURE VALUE
                  </span>

                  <p
                    className={`font-mono text-xs leading-relaxed p-3 border border-[#D4AF37]/15 ${
                      isDark
                        ? 'bg-gray-500/5 text-gray-300'
                        : 'bg-gray-50 text-gray-700'
                    }`}
                  >
                    {formatValue(reason.value)}
                  </p>
                </div>

                <div className="space-y-1.5">
                  <span className="text-[10px] font-mono uppercase tracking-[0.2em] text-[#D4AF37] block">
                    SHAP CONTRIBUTION
                  </span>

                  <p
                    className={`font-mono text-xs leading-relaxed p-3 border border-[#D4AF37]/15 ${
                      isDark
                        ? 'bg-gray-500/5 text-gray-300'
                        : 'bg-gray-50 text-gray-700'
                    }`}
                  >
                    {formatShapValue(
                      reason.shap_value
                    )}
                  </p>
                </div>

                <div className="space-y-1.5">
                  <span className="text-[10px] font-mono uppercase tracking-[0.2em] text-gray-400 block">
                    MODEL EXPLANATION
                  </span>

                  <div className="flex items-start gap-3">
                    {increasesThreat ? (
                      <AlertTriangle className="w-4 h-4 text-red-400 mt-0.5 shrink-0" />
                    ) : (
                      <CheckCircle2 className="w-4 h-4 text-[#D4AF37] mt-0.5 shrink-0" />
                    )}

                    <p className="font-sans text-xs text-gray-400 leading-relaxed">
                      This feature{' '}
                      {increasesThreat
                        ? 'increases'
                        : 'decreases'}{' '}
                      the predicted threat according to
                      the SHAP contribution generated by
                      the trained tree model.
                    </p>
                  </div>
                </div>

                <div className="space-y-1.5">
                  <span className="text-[10px] font-mono uppercase tracking-[0.2em] text-[#D4AF37] block">
                    FEATURE ATTRIBUTION
                  </span>

                  <p className="font-sans text-xs text-gray-300 leading-relaxed">
                    Feature{' '}
                    <strong className="text-[#D4AF37]">
                      {reason.feature || 'N/A'}
                    </strong>{' '}
                    had a SHAP contribution of{' '}
                    <strong className="text-[#D4AF37]">
                      {formatShapValue(
                        reason.shap_value
                      )}
                    </strong>{' '}
                    to this prediction.
                  </p>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {prediction?.policyReason && (
        <div
          className={`p-6 border border-[#D4AF37]/20 ${
            isDark ? 'bg-black' : 'bg-white'
          }`}
        >
          <span className="text-[10px] font-mono uppercase tracking-[0.2em] text-[#D4AF37] block mb-2">
            ML POLICY REASON
          </span>

          <p className="text-xs text-gray-400 leading-relaxed">
            {prediction.policyReason}
          </p>
        </div>
      )}
    </div>
  );
};